Fj 2024 lesson 2
stukenvitalii/T-Fintech-Course pull request #2
Opened 2024-09-01 11:22 UTC by stukenvitalii

2024-09-05 06:30 UTC, SHvatov requested changes
@stukenvitalii оставил пару комментов, посмотри их, пожалуйста.

2024-09-05 06:30 UTC, SHvatov commented on city-error.json
> +{
Давай файлы унесем в `resources`

2024-09-05 06:30 UTC, SHvatov commented on build.gradle
> +    compileOnly 'org.projectlombok:lombok:1.18.34'
Не вижу зависимости для логгера, добавь плиз)

2024-09-05 06:30 UTC, SHvatov commented on build.gradle
> +    compileOnly 'org.projectlombok:lombok:1.18.34'
Вижу, что используещь стандартный. Давай докинем кого-ниубдь вроде того же slf4j, чтобы я докинул тебе баллов)

2024-09-05 06:30 UTC, SHvatov commented on src/main/java/edu/tbank/Main.java
> +
Лишние пустые строки давай уберем

2024-09-05 06:30 UTC, SHvatov commented on src/main/java/edu/tbank/Main.java
> +        File file = new File("city.json");
Чисто на будущее - при работе с IO всегда стоит проверять, а готово ли оно к работе) В данном случае - что файл есть и он реально файл)

2024-09-05 06:30 UTC, SHvatov commented on src/main/java/edu/tbank/Main.java
> +            logger.log(Level.SEVERE, e.getMessage());
Попробуй придумать кейсы, в которых можно было бы использовать и другие уровни логгирования.

2024-09-05 06:30 UTC, SHvatov commented on src/main/java/edu/tbank/dto/City.java
> +public class City implements Serializable {
Чисто рекомендация - так как этот класс - это DTO, поля можно сделать `final`, а от дефолтного и all args конструкторов можно избавиться. Но можно оставить и так)

2024-09-05 06:30 UTC, SHvatov commented on src/main/java/edu/tbank/parser/XmlParser.java
> +    private XmlParser() {}
`@UtilityClass` :)

2024-09-05 06:30 UTC, SHvatov commented on src/main/java/edu/tbank/parser/XmlParser.java
> +        XmlMapper xmlMapper = new XmlMapper();
Создавать по мапперу на каждый вызов - слишком расточительно. Я бы вынес его в отдельное поле в `XmlParser`. Поле можно оставить и статическим, но если мы говорим про spring-way, то лучше сделать его нестатическим, и иметь возможность передать через конструктор.

2024-09-05 11:17 UTC, stukenvitalii commented
@SHvatov все поправил)

2024-09-12 12:48 UTC, SHvatov approved these changes
🔥, можно мерджить)

2024-09-12 12:50 UTC, merged