Fj 2024 lesson 5
stukenvitalii/T-Fintech-Course pull request #4
Opened 2024-09-23 19:35 UTC by stukenvitalii

Основное все сделал, осталось реализовать AOP и поправить мелкие моменты

2024-09-23 22:03 UTC, stukenvitalii commented
Реализовал AOP, вынес все в отдельный стартер. вроде все отлично работает)
![image](https://github.com/user-attachments/assets/67e15954-0154-4a51-b438-fd5526f040d1)

2024-09-29 19:19 UTC, SHvatov requested changes
@stukenvitalii идеи и реализация 🔥, оставил пару комментариев - посмотри их, пожалуйста)

2024-09-29 19:19 UTC, SHvatov commented on measurement-logging-starter/src/main/java/org/tinkoff/measurementloggingstarter/annotation/EnableTimeMeasurementLogging.java
> +public @interface EnableTimeMeasurementLogging {}
Звучит как более конфигурационная аннотация, типа того же `EnableScheduling`, которая за собой несет кучу автоконфигов и множество бинов. Давай дадим более простое название, типа `Timed` или типа того.

2024-09-29 19:19 UTC, SHvatov commented on measurement-logging-starter/src/main/java/org/tinkoff/measurementloggingstarter/annotation/EnableTimeMeasurementLoggingAspect.java
> +        log.info("============================================================================================================");
Красивое?) В продакшене такие логи не стоит выводить - если у нас пишется много логов, они могут быть очень далеко друг от друга)

2024-09-29 19:19 UTC, SHvatov commented on measurement-logging-starter/src/main/resources/META-INF/spring.factories
> +org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
О, красивое! Только оно работает? Там вроде поменяли с spring.factories на такое:

<img width="777" alt="image" src="https://github.com/user-attachments/assets/26b190a0-44b3-46da-8dce-36fd621224fe">

Или они в 3.3 поправили этот косяк с обратной совместимостью?

2024-09-29 19:19 UTC, SHvatov commented on measurement-logging-starter/src/main/resources/META-INF/spring.factories
> +org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
https://habr.com/ru/articles/806217/

2024-09-29 19:19 UTC, SHvatov commented on src/main/java/edu/tbank/hw5/Application.java
> +@SpringBootApplication(scanBasePackages = {"edu.tbank.hw5", "org.tinkoff.measurementloggingstarter"})
Вот поэтому у тебя стартер работает) А надо бы, чтобы без `scanBasePackages`. Выше написал почему не работает.

2024-09-29 19:19 UTC, SHvatov commented on src/main/java/edu/tbank/hw5/client/KudaGoClient.java
> +            return restTemplate
Обсудили использование `RestTemplate`)

2024-09-29 19:19 UTC, SHvatov commented on src/main/java/edu/tbank/hw5/repository/CategoryRepository.java
> +public class CategoryRepository {
Структура репозиториев +- одинаковая, давай пока что вынесем в абстракцию) А потом уже будем юзать полноценно Spring Data)

2024-09-29 19:27 UTC, stukenvitalii commented on src/main/java/edu/tbank/hw5/Application.java
> +@SpringBootApplication(scanBasePackages = {"edu.tbank.hw5", "org.tinkoff.measurementloggingstarter"})
Да, все именно так) перепробовал все, помог только этот параметр

2024-09-29 19:45 UTC, stukenvitalii commented on measurement-logging-starter/src/main/resources/META-INF/spring.factories
> +org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
Ура, заработало!

2024-09-29 19:55 UTC, stukenvitalii commented on src/main/java/edu/tbank/hw5/repository/CategoryRepository.java
> +public class CategoryRepository {
там просто проблема в том, что у Category id это int, а у Location id - String, поэтому в абстракцию странновато выносить, мне кажется. Ну либо можно просто добавить генерацию id у локаций и тогда все супер будет

2024-09-29 19:56 UTC, stukenvitalii commented on src/main/java/edu/tbank/hw5/repository/CategoryRepository.java
> +public class CategoryRepository {
ну хотя можно и вынести без этого, согласен

2024-10-01 19:20 UTC, SHvatov commented on src/main/java/edu/tbank/hw5/repository/CategoryRepository.java
> +public class CategoryRepository {
Generic'и вам в помощь)

2024-10-01 19:52 UTC, stukenvitalii commented on src/main/java/edu/tbank/hw5/repository/CategoryRepository.java
> +public class CategoryRepository {
да, уже сделал)

2024-10-04 12:57 UTC, SHvatov approved these changes
@stukenvitalii 🔥 🚀

2024-10-04 20:33 UTC, merged