Fj 2024 lesson 8
stukenvitalii/T-Fintech-Course pull request #8
Opened 2024-10-04 20:32 UTC by stukenvitalii

2024-10-05 10:00 UTC, stukenvitalii commented
Swagger доку добавил)
![image](https://github.com/user-attachments/assets/bb0cfc3c-3d39-4c63-b9ff-fe70f10f8e77)

2024-10-13 15:42 UTC, SHvatov requested changes
@stukenvitalii оставил пару комментариев, посмотри их пожалуйста)

2024-10-13 15:42 UTC, SHvatov commented on measurement-logging-starter/src/main/java/org/tinkoff/measurementloggingstarter/MeasurementLoggingApplication.java
> +public class MeasurementLoggingApplication {
@stukenvitalii давай привдем эту ветку к текущему состоянию мастера, чтобы не было старых диффов. А то я человек малодушный, а 2к строк изменений в такой небольшой домашке меня пугают)

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/client/BankClient.java
> +                .uri("/XML_daily.asp/")
Это бы в константу

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/client/BankClient.java
> +public class BankClient {
`CentralBankApiClient`, а то я долго думал, что это какая-то сущность, описывающая клиента банка в прямом смысле этого словосочетания)

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/dto/ValuteDto.java
> +public record ValuteDto(@JsonProperty("currency") @NotNull String charCode,
<img width="789" alt="image" src="https://github.com/user-attachments/assets/23ca14e9-a224-4a84-a34d-852834457847">

Вроде бы мы не в Румынии) Чем не подошла классическая `Currency`?

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/client/BankClient.java
> +                    throw new HttpServerErrorException(HttpStatusCode.valueOf(503));
Хм, а мы прямо всегда недоступны, когда ЦБ нам пятисотит?

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/client/BankClient.java
> +        if (valCursResponse == null) {
И еще такой вопрос - а `getBody` реально может null вернуть? С учетом вызова `toEntity`.

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/client/BankClient.java
> +        log.warn("Api is unavailable! Fallback method fallbackDailyRates triggered due to {} ", throwable.getMessage());
Еще бы хорошо чисто `throwable` в лог закинуть, чтобы у нас в логах был полный стек-трейс и мы знали, куда смотреть.

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/configuration/CacheConfig.java
> +        Objects.requireNonNull(cacheManager().getCache("dailyRates")).clear();
:ok:

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/configuration/WebConfig.java
> +    public HttpMessageConverter<Object> createXmlHttpMessageConverter() {
Я бы назвал это `RestClientConfig`, все-таки тут мы настраиваем десериализаторы для него)

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/configuration/WebConfig.java
> +    public HttpMessageConverter<Object> createXmlHttpMessageConverter() {
И, может быть, я бы это объединил с `CurrencyClientConfiguration`, но это чисто на твое усмотрение.

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/controller/CurrencyApi.java
> +public interface CurrencyApi {
Честно говоря, вынесение отдельного интерфейса для контроллера не дает какого-то профита, ибо контроллер и без того уже является сущностью наивысшего уровня абстракции)

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/controller/CurrencyApi.java
> +public interface CurrencyApi {
То есть, в идеале, в методе контроллера должен быть вызов сервиса и его спецификация.

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/entity/ValCurs.java
> +public class ValCurs {
Все-таки стоит стараться давать сущностям англоязычные названия)

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/exception/response/NotFoundErrorResponse.java
> +    private int code;
А код точно нужен? Вроде как он дублирует статус ответа, а в большинстве реализаций клиентов для апи, до тела почти что не добраться в случае ошибок на уровне статуса. 

То есть, если бы ты всегда отдавал 200 - то ок, а так - просто дублирование информации)

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/service/impl/CurrencyCacheServiceImpl.java
> +    public List<ValuteDto> getDailyRates() {
Тогда, наверное, стоит класс назвать просто `CurrencyCache`, + можно посмотреть в сторону использования стандартного `Cacheable`

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/service/impl/CurrencyServiceImpl.java
> +                .filter(valuteDto -> valuteDto.charCode().equals(code))
я бы сравнение делал наоборот, не `valueDto.charCode == code`, а `code == valueDto.charCode`, чтобы NPE избежать. Если у тебя, конечно, где-то сверху нет проверок в `valueDto`

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/repository/CurrencyRepository.java
> +public class CurrencyRepository {
кажется, что данная абстракция особо не нужна, как и кэш

кэш стоит сделать приватной деталью реализации клиента, чтобы конечный пользователь не знал о его наличии, а от репозитория стоит просто избавиться, ибо это лишняя прослойка.

2024-10-13 15:42 UTC, SHvatov commented on src/main/java/edu/tbank/hw8/service/impl/CurrencyServiceImpl.java
> +    private double getRate(String currencyCode) {
Я бы советовал использовать `BigDecimal` для работы с деньгами, чтобы была повышенная точность вычислений)

2024-10-25 10:52 UTC, stukenvitalii commented
@SHvatov

2024-10-25 14:35 UTC, SHvatov approved these changes
@stukenvitalii 🆗

2024-10-25 14:51 UTC, merged