Fj 2024 lesson 9
stukenvitalii/T-Fintech-Course pull request #9
Opened 2024-10-11 17:44 UTC by stukenvitalii

2024-10-11 17:49 UTC, stukenvitalii commented
Вот результаты выполнения с разным кол-вом потоков(0 - до многопоточки) 
![image](https://github.com/user-attachments/assets/a83b854e-d413-4e5e-bb1b-490a818a28ec)
![image](https://github.com/user-attachments/assets/90a99c6a-77d2-4223-929c-66e18781efa1)
Видно, что результаты с учетом небольшой погрешности одинаковые. 
Скорее всего, такое поведение можно объяснить тем, что запросы на API выполняются синхронно, то есть мы ждем пока придет ответ от API и весь поток блокируется. Если бы использовали WebClient, результаты были бы другие - уменьшение времени по сравнению с однопоточным выполнением.

2024-10-11 17:52 UTC, stukenvitalii commented
Попробую доказать свои слова))

2024-10-11 18:14 UTC, stukenvitalii commented
https://github.com/stukenvitalii/T-Fintech-Course/pull/10 реализовал с веб клиентом, настроил пулинг для множества одновременных запросов. Стало еще дольше(около 2000 мс в среднем) и опять же нет особой разницы в количестве потоков)

2024-10-22 18:49 UTC, stukenvitalii commented
1. Использование ExecutorService и Future - добавил конфигурацию потоков, сделал инициализацию данных многопоточно, замеры сделал(см. начало ПР)
2. Использование CompletableFuture - создан EventController, который возвращает события по бююджету за указанный промежуток времени. 
P.S. далее это будет переписано с использованием ProjectReactor. Реализация до изменения https://github.com/stukenvitalii/T-Fintech-Course/tree/6082ecb58a67af6bf860ee93d11102a2c2f0a653 (коммит [6082ecb](https://github.com/stukenvitalii/T-Fintech-Course/pull/9/commits/6082ecb58a67af6bf860ee93d11102a2c2f0a653))
3. Project Reactor - переписал все с использованием ProjectReactor
4. Kotlin Coroutines - ссылка на PR на платформе, на всякий случай оставлю еще здесь [fj_2024_lesson_9](https://github.com/stukenvitalii/T-Fintech-Course_Kotlin/pull/2)
5. Доработка клиентов для внешнего АПИ - тоже реализовал на Kotlin

2024-10-25 10:45 UTC, SHvatov commented
@stukenvitalii красота!! Мой респект и уважение за такую презентацию результатов))

2024-10-25 10:49 UTC, SHvatov requested changes
@stukenvitalii 🔥, пара комментов, и можно мерджить)

2024-10-25 10:49 UTC, SHvatov commented on src/main/java/edu/tbank/hw5/bootstrap/DataLoader.java
> +    private Mono<String> fetchData(String type) {
`type` можно сделать енумом, и я бы метод разделил на два, чтобы проще было читать)

2024-10-25 10:49 UTC, SHvatov commented on src/main/java/edu/tbank/hw5/bootstrap/DataLoader.java
> +        return Mono.just("invalid type");
И с енамом от этого можно будет избавиться

2024-10-25 10:49 UTC, SHvatov commented on src/main/java/edu/tbank/hw5/bootstrap/DataLoader.java
> +        schedulingExecutorService.shutdown();
👍

2024-10-25 10:49 UTC, SHvatov commented on src/main/java/edu/tbank/hw5/repository/EventRepository.java
> +    public Mono<Flux<Event>> getEventsByBudget(LocalDate dateFrom, LocalDate dateTo) {
Вот это оверкилл немного)

Mono и Flux - оба паблишеры, основное отличие которых в том, что первый - это поток данных из 0 или 1 элементов, а второй - из 0 до бесконечности. Поэтому оборачивать их не нужно)

2024-10-25 10:49 UTC, SHvatov commented on src/main/java/edu/tbank/hw5/service/impl/EventServiceImpl.java
> +                    Double budgetInRubles = tuple.getT2();
Double -> BigDecimal

2024-10-25 10:51 UTC, stukenvitalii commented
> @stukenvitalii 🔥, пара комментов, и можно мерджить) окей, поправлю сегодня)
P.S. посмотри еще пожалуйста предыдущее дз, я там все поправил

2024-10-27 22:40 UTC, stukenvitalii commented
@SHvatov все поправил)

2024-10-27 22:44 UTC, merged